### PR TITLE
Filter bug fixes

### LINKED ISSUE #117: Filter component bugs
When using the new filter system in an actual project, I noticed a few bugs:

- Typescript issues
    - Generics required for FilterHooks interface
    - Generics required for useFilter hook and a couple functions within the hook (getApiPostBody, applyApiPostBody)
    - Less restrictive type required for ContextSwitchMenuProps values
- General Issues
    - MultiSelectFilter.getFilterCount does not account for undefined value as input
    - ListFilter.getFilterCount does not account for undefined value as input
    - ListFilter options (checkbox) color not applied
    
        image

    - FilterValueChipsContainer requires `flexWrap: ‘wrap’` to properly display multiple lengthy chips.
    
       Multi Select Filter

### PR DESCRIPTION
**Pull request by jason-ransom-slalom**
This PR addresses a number of bugs (#117) discovered when implementing the filter system. If approved, this will close #117.

image

### CODE REVIEW

File: src/Filter/modules/ListFilter/ListFilter.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ const ListFilter = (
     listFilterOptions: ListFilterOptions = {},
     listFilterOverrides: ListFilterOverrides = {}
 ): FilterModule<Set<string>> => ({
-    getFilterCount: (value) => value.size,
+    getFilterCount: (value) => value?.size || 0,
```
Comment (michaelpuzon) [inline src/Filter/modules/ListFilter/ListFilter.tsx:34]: This should be '??' instead.

Comment (jason-ransom-slalom) [reply src/Filter/modules/ListFilter/ListFilter.tsx]: Good catch. Updated.

**Review by michaelpuzon — APPROVED** [review]

**Review by JonTheBurley — APPROVED** [review]

File: src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx [hunk 2]
```diff
@@ -28,7 +28,7 @@ const MultiSelectFilter = (
     }: MultiSelectFilterProps,
     multiSelectFilterOptions: MultiSelectFilterOptions = {}
 ): FilterModule<string[]> => ({
-    getFilterCount: (value) => value.length,
+    getFilterCount: (value) => value?.length || 0,
```
Comment (adorack-tri) [inline src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx:31]: I'm pretty sure @michaelpuzon 's comment above about `??` should apply here as well.  (I'm assuming it's mostly a stylistic suggestion that we should default to `??` to avoid errors in general, rather than that using `??` over `||` avoids a specific bug in that case.)

**Review by adorack-tri — CHANGES_REQUESTED** [review]

File: src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx (hunk 2 above)
Comment (jason-ransom-slalom) [reply src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx]: Thanks! Got this one now as well.

**Review by adorack-tri — APPROVED** [review]
