### PR TITLE
Multi select filter duplicates fix

### LINKED ISSUE #138: MultiSelectFilter drop list has duplicate entries
When all values are cleared using the `MultiSelectFilter` module and an `initialValue` has been provided, that value appears twice in the list. 

image

Repro steps:

1. Navigate to [MultiSelectFilter Story](https://toyotaresearchinstitute.github.io/lakefront/?path=/docs/lakefront-filter-multiselectfilter--multi-select-filter)
2. Expand the MultiSelect Filter.
3. Clear out all values.
4. Expand the dropdown by clicking on the empty input.

Suggested Fix:
Create/Apply a function to the [MultiSelect](https://github.com/ToyotaResearchInstitute/lakefront/blob/main/src/Filter/modules/MultiSelectFilter/MultiSelect.tsx) component state initialization to filter the initial `items` down to unique items by comparing the `value` property of each item (e.g. no initial items should have the same item.value).

### PR DESCRIPTION
**Pull request by alex-maul**
Closing this PR will resolve issue #138 
Added method to filter out duplicated selectable options when placeholder is removed.

Screen Shot 2022-11-01 at 9 33 56 AM

### Lakefront PR Checklist

- [ ]  Exported any new components in the src/index.ts
- [ ]  Updated the main README table.
- [x]  Ensure version numbers were bumped properly.
- [ ]  Imported SVGs with relative path, if applicable.
- [x]  Removed any irrelevant commit messages from merge commit.
- [ ]  Deleted branch after merge.

### CODE REVIEW

File: src/components/Filter/modules/MultiSelectFilter/multiSelectUtil.ts [hunk 1]
```diff
@@ -17,3 +17,7 @@ export const parseItems = (item: string, delimiter?: string): string[] => {
         .map((a) => a.trim())
         .filter((a) => a);
 };
+
+export const getUniqueOptions = (itemsStateCopy: MultiSelectOption[]): MultiSelectOption[] => {
+    return itemsStateCopy.filter((unique, index) => unique.value.indexOf(unique.value) !== index);
```
Comment (jason-ransom-slalom) [inline src/components/Filter/modules/MultiSelectFilter/multiSelectUtil.ts:22]: This code doesn't quite work expected. You can check by changing the `itemsStateMock` in the test to look like the following:
```ts
const itemsStateMock =
            [
                { 'label': 'colors', 'value': 'colors' },
                { 'label': 'sizes', 'value': 'sizes' },
                { 'label': 'shapes', 'value': 'shapes' },
                { 'label': 'colors', 'value': 'colors' },
                { 'label': 'colors', 'value': 'colors' }
            ];
```

I think instead of doing `unique.value.indexOf` (which checks if the provided string appears in the value), we instead need to be building a new array and checking if there is already an item in that array with the same value.

**Review by jason-ransom-slalom — CHANGES_REQUESTED** [review]

**Review by jason-ransom-slalom — APPROVED** [review]
LGTM

**Review by amirkibbar — APPROVED** [review]
