### PR TITLE
Fix list filter

### LINKED ISSUE #142: Filter module getBrowserQueryUrlValue implementations broken
It appears the latest `getBrowserQueryUrlValue` changes have caused unexpected issues. Since the value that is output from this method [gets stringified here using query-string](https://github.com/ToyotaResearchInstitute/lakefront/blob/151b2b9f518c22f4676c5446c1b1395a23ede393/src/Filter/util/filterHooks.tsx#L47), non-string/number filters are not being correctly applied. While multiple values appear correct in the demo URL bar (for instance `multiSelectFilter=colors&multiSelectFilter=sizes` when demoing the MultiSelectFilter), the actual value (`multiSelectFilter=colors%2Csizes`) is a stringified array and thus incorrect.

Please revert the methods back to their original implementation and update the typing/docs to reflect that the value can be any valid javascript object.

### PR DESCRIPTION
**Pull request by jason-ransom-slalom**
This PR addresses an issue where the values output by the `getBrowserQueryUrlValue` method of some filter modules was now incorrect. If approved, this will close #142.

image

### CODE REVIEW

File: src/Filter/types/index.ts [hunk 1]
```diff
@@ -55,8 +55,11 @@ export interface FilterModule<T> {
     getApiPostBody(key: string, value: T): FilterPostBody | null | undefined;
     /**
      * Generates the url query param value(s) for saving filter value(s) in the browser address bar (key is automatic).
+     * **Note: The output value here can be any valid object
+     * of type `Record<string, any>` as it will be stringified in the useFilter hook using the query-string library
+     * defaults (https://github.com/sindresorhus/query-string)**.
```
Comment (adorack-tri) [inline src/Filter/types/index.ts:60]: Thanks for the documentation -- sorry for leading us down a false path.

**Review by adorack-tri — APPROVED** [review]

File: src/Filter/types/index.ts (hunk 1 above)
Comment (jason-ransom-slalom) [reply src/Filter/types/index.ts:60]: No, you're good! Didn't entirely understand how the implementation before myself. Glad to know going forward and allowed us to add this documentation.

**Review by JonTheBurley — APPROVED** [review]
